### ISSUE TITLE
Rolling back the firmware

### ISSUE THREAD

**Issue by br0cker** [NARUTOfzr/Neptune_3_Pro_Plus_Max#24]
Hi. 

I have updated the screen firmware to 1_5beta_20230114.tft. I wanted to bring back the firmware, but when updating I get a message: Model does not match, TJC4827X243_011C, File info ERROR! 
I tried [V1_4_1_20230210.tft]  [elegooui_20221122.tft]
And I still get this message. Please help me.

Neptune 3 Pro

**Comment by BenKmann** [comment]
Hi, 
my Fan starts working at around the third layer. Have you tried waiting?

**Comment by NARUTOfzr** [comment]
@br0cker 
1. Download the firmware package and decompress it to obtain the firmware.
![image](https://user-images.githubusercontent.com/64059773/220386817-d7efaedc-1535-4bc7-bb84-9c7607272eb8.png)

2. Format TF card to FAT32 4096 bytes
3. Update the screen firmware

**Comment by NARUTOfzr** [comment]
> Hi, my Fan starts working at around the third layer. Have you tried waiting?

This is usually set by the slicing software:
![image](https://user-images.githubusercontent.com/64059773/220389191-86504196-4cf0-43b3-a469-af4fce218fd5.png)

**Comment by br0cker** [comment]
> 

Hi. 
Thank you very much. I did it. 
My mistake was that I did not download the entire archive, but the files separately. 
Good luck.

**Comment by br0cker** [comment]
> Hi,
> my Fan starts working at around the third layer. Have you tried waiting?

Hi. 
Thanks for the reply. I was scared, I thought it was because of the new firmware. It turned out that everything is exactly as you write. Have a nice day.
