### ISSUE TITLE
Update in Progress blocked

### ISSUE THREAD

**Issue by giova609** [NARUTOfzr/Neptune_3_Pro_Plus_Max#32]
After trying to update the Neptune 3 PRO to firmware 1.1.5.1a it got stuck on "Update in Progress". Even if you remove the TF Card, "Update in Progress" still appears. Thank you

**Comment by NARUTOfzr** [comment]
According to firmware update instructions. Try to download the entire zip package. Then format the TF card. Update the mainboard firmware.




---Original---
From: ***@***.***&gt;
Date: Mon, Mar 13, 2023 03:35 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [NARUTOfzr/Neptune_3_Pro_Plus_Max] Update in Progress blocked (Issue#32)




 
After trying to update the Neptune 3 PRO to firmware 1.1.5.1a it got stuck on "Update in Progress". Even if you remove the TF Card, "Update in Progress" still appears. Thank you

**Comment by giova609** [comment]
Thanks for the help, the zip file is asking me for a password.  I use Edge Chromiun with web browser.

**Comment by NARUTOfzr** [comment]
Trying to reload the firmware 1.1.5.1a won't work either?

**Comment by giova609** [comment]
I've tried both reloading 1.1.5.1a and the beta, but it gets stuck on "Update firmware..."
Il 13 mar 2023, 16:39 +0100, 冯 ***@***.***>, ha scritto:

**Comment by NARUTOfzr** [comment]
Hi@giova609 
Check whether the LED on the motherboard lights up? 
Maybe you can shoot a firmware update video to confirm the current situation.

**Comment by giova609** [comment]
Thanks for the help. I solved. I reloaded all the firmware starting from 1.1.4.1 (present on the printer before the problem) up to 1.1.5.1a.
