### ISSUE TITLE
1.1.5.1a release firmware led wobblin problem

### ISSUE THREAD

**Issue by ramazandagli** [NARUTOfzr/Neptune_3_Pro_Plus_Max#39]
The problem is when i started print led brightnes wobbling. I checked cables and gcode all looks fine. When printer doesn't print anything leds are stable not brightnes wobbling at all. Is it normal or not ? Thanks for helps.

**Comment by coddiewomple** [comment]
i that where my printer i would be getting a multimeter out to monitor the voltage into the led strip to see if there might be a power supply problem and maybe disconnect the led to see if it restores full printer function. It is possible for those smd leds to got funny after they get hot just like in a tv so sounds like you would be advised to contact elegoo support direct for that issue if it still happens with different firmware perhaps even stock fw.

**Comment by ramazandagli** [comment]
I doubt the firmware because there was no problem in the stock version. Can you tell me if you have a recommended firmware version, thanks
