### ISSUE TITLE
1.5-Beta屏幕固件背光BUG(1.5-beta screen firmware backlight BUG)

### ISSUE THREAD

**Issue by funnygeeker** [NARUTOfzr/Neptune_3_Pro_Plus_Max#44]
当我将背光设置到最低时，屏幕就直接关闭了背光，这导致我看不到屏幕上的任何内容，一般来说，应该限制屏幕背光的最低值。
（When I set the backlight to a minimum, the screen directly turns off the backlight, which causes me to see nothing on the screen. You should limit the minimum screen backlight.）

**Comment by NARUTOfzr** [comment]
@funnygeeker 感谢您的反馈！  :smile:  我们在UI版本V1.4.2做了修复，目前我还在测试UI固件以及主板固件的稳定性，不久后就会发布。
