### ISSUE TITLE
Where is firmware files?

### ISSUE THREAD

**Issue by valkuc** [NARUTOfzr/Neptune_3_Pro_Plus_Max#51]
Hi. I see you updated readme file with info regarding new firmware version (1.x.5.1b for board and 1.4.2 for screen), but there is no downloadable files. Am I missing something?

See https://github.com/NARUTOfzr/Neptune_3_Pro_Plus_Max/tree/main/board%20firmware/Neptune3Plus

**Comment by ChrisCopter** [comment]
Go to Code, than klick the green code button and download zip.

**Comment by valkuc** [comment]
> Go to Code, than klick the green code button and download zip.

The last version in the repository is 1.2.5.1a-20230210, but in the readme file 1.x.5.1b is mentioned.

![изображение](https://github.com/NARUTOfzr/Neptune_3_Pro_Plus_Max/assets/6421082/678842c9-4e3c-4c2a-abf6-627154fa8f41)

**Comment by NARUTOfzr** [comment]
@valkuc @ChrisCopter Sorry for the confusion! This part of the file has not been uploaded, I will arrange as soon as possible.

**Comment by ramdaron** [comment]
> @valkuc @ChrisCopter Sorry for the confusion! This part of the file has not been uploaded, I will arrange as soon as possible.

Please also upload the source code of the LCD. I plan to send a pull request with fixes in Russian localization.
Thank you!

**Comment by NARUTOfzr** [comment]
@valkuc @ChrisCopter V1.4.2-1.x.5.1b ：Firmware has been uploaded.

@ramdaron The UI-HMI project file has been updated.     https://github.com/NARUTOfzr/Neptune_3_Pro_Plus_Max/tree/main/Source%20Code/LCD-TJC/V1.4.2

**Comment by valkuc** [comment]
Thx!
