### ISSUE TITLE
Doesn't Save Fan Control Settings

### ISSUE THREAD

**Issue by AhmedShaalan** [NARUTOfzr/Neptune_3_Pro_Plus_Max#52]
I have updated my machine to 1.4.1 for the screen, and 1.1.5.1a for the board.
and since then, I enable Fan Control from the Settings Menu. However, the settings gets turned off automatically between print jobs and when the machine turns off.

I think this is critical because it might melt down the extruder.

**Comment by NARUTOfzr** [comment]
@AhmedShaalan When the temperature at the hot end is higher than 50 ° C, the fan at the hot end automatically starts. The fan turned on in this setting is the model cooling fan.
Model cooling fan on both sides of the print head: Usually turned on when printing the second layer, this is controlled by the G-code of the print file, which will be turned off when printing is complete.
