### ISSUE TITLE
Don´t get it what the newest version is

### ISSUE THREAD

**Issue by ChrisCopter** [NARUTOfzr/Neptune_3_Pro_Plus_Max#54]
Hey Guys i don´t get it what the newest version of the firmware is.
In the update log 1.5.1 is mentioned after 5.1.3.
But the number on the last one is higher so i don´t get it, feeling retardet.
Sorry, may anyone help with this to get it clear.

**Comment by NARUTOfzr** [comment]
@ChrisCopter They have compatibility issues with UI versions. No further maintenance updates have been made to the 1.5-beta UI release.

**Comment by ChrisCopter** [comment]
So 1.x.5.1b is the latest most updated stable release for the board firmware?
Or is the version 1.x.5.3 more updated?
Sorry my confusion is maxed out. 🙈

**Comment by RandomAlec** [comment]
@ChrisCopter if your final intention is to be on what works and is stable, I would follow the chart as shown for compatibility, meaning you want to update to 1.1.5.1a if you haven't done so already (and UI version 1.4.1).

![image](https://github.com/NARUTOfzr/Neptune_3_Pro_Plus_Max/assets/38933128/03922c45-9b9d-4589-90e7-ab1e251baf44)

**Comment by LarsStegman** [comment]
I think it would also be a good idea if the GitHub releases feature is used, that way the versions are released together, which makes it easier to see what releases there are.

**Comment by afruzu** [comment]
What a great confusion with this numbers! I suggest to change to a simplest way to distingush between  the three models (i.e. with a letter instead of a number) and rhen to adopt the same number for motherboard and screen firmware, almost for stable release.

**Comment by AhmedShaalan** [comment]
Can we downgrade board and screen firmware?

**Comment by afruzu** [comment]
downgrade is always possible, keep in mind that previously the firmware ran on the machine without subsequent upgrades. I'm curious, however, to know for what strange reason you would want to go back ...

**Comment by AhmedShaalan** [comment]
It's a beta version, so I expect to have issues here or there. So, I wanted to make sure I have a way out.

**Comment by NARUTOfzr** [comment]
Sorry for the confusion. The firmware file has been updated, you can try to update the firmware.
I also try to release versions, but I still need to learn how to use it.
